### ISSUE TITLE
mypy support

### ISSUE THREAD

**Issue by eroller** [wheerd/multiset#114]
just started using multiset in my project and got these mypy messages:

Mypy found 1 error, 1 note  in 1 file
verify_pgx_json_call.py : 1 error, 1 note 
Skipping analyzing "multiset": module is installed, but missing library stubs or py.typed marker  [import] (5:0)
See https://mypy.readthedocs.io/en/stable/running_mypy.html#missing-imports (5:0)

Any plan to add full type support to the library?

**Comment by wheerd** [comment]
Sorry for the late reply, I don't plan to add full type support but I'm happy to accept a PR if someone wants to do the work. I just don't have the capacity or interest to do it myself.

**Comment by bakert** [comment]
Thanks for this awesome library! I much prefer it to Counter for my purposes, but I'd love to be able to type my Multisets and Frozenmultisets the same way I can type a set or a frozenset.

Luckily it seems almost all the work has already been done. There's a `py.typed`, and a `multiset.pyi` from a few years back that's 99% there. Unfortunately when installing from pypi `py.typed` and `multiset.pyi` are not included. 

After reading a lot of docs and people with similar issues I came to the conclusion that the only way to get these files included is to convert the repo from "single file module" style to "package style". I did this in https://github.com/wheerd/multiset/pull/127 and it seems to work great. 100% backwards-compatible change.

Please let me know what you think on that PR!
