### ISSUE TITLE
What happened to popitem?

### ISSUE THREAD

**Issue by odioidentisti2** [wheerd/multiset#13]
I tried versions 2.1.1 and 2.0.3: both are missing the popitem() and keys() methods (but they are described in the doc). And apparently nothing replaced it.
Is this a feature or a bug?

Furthermore,  the button "docs" links to doc version 2.0.4, for all the versions available.

**Comment by wheerd** [comment]
They indeed seem to be missing. I would be happy to accept a pull request that (re)adds them. I don't have time to add it myself at the moment.
