### ISSUE TITLE
TypeError: type 'FrozenMultiset' is not subscriptable

### ISSUE THREAD

**Issue by ldeluigi** [wheerd/multiset#136]
I'd like to be able to write type hints with generic typing in the form `FrozenMultiset[T]` but the interpreter complaints, Could you extend `Generic[T]` from the `typing` package and then write typeing for the methods?

**Comment by ldeluigi** [comment]
I can open a PR if you prefer

**Comment by wheerd** [comment]
Thank you for the issue, I would be happy to accept a PR for this. At the moment I don't have the capacity to work on it myself :)
