### ISSUE TITLE
Can't load from pickle

### ISSUE THREAD

**Issue by adaldo** [wheerd/multiset#2]
I have an `AttributeError` when I try to load a `FrozenMultiset` with `pickle.load`.
Namely, this code raises an `AttributeError` on line 118 of `multiset.py` when trying to access the `_elements` attribute.

```python
import pickle as pk
import multiset as ms

fms = ms.FrozenMultiset("aabcd")
    
with open("my_file","w") as my_file:
    pk.dump(fms, my_file)

with open("my_file", "r") as my_file:
    fms_copy = pk.load(my_file)
```

**Comment by wheerd** [comment]
Version 2.0.3 fixes this problem.
