### ISSUE TITLE
Why sometimes the Multiset is not disordered???

### ISSUE THREAD

**Issue by bigfatcat-shiquan** [wheerd/multiset#24]
Look at these samples:

Input:
{
FrozenMultiset([frozenset({'b'}) , frozenset({'a'})])
} == {
FrozenMultiset([frozenset({'a'}) , frozenset({'b'})])
}
Output: False

Input:
{
frozenset([frozenset('b') , frozenset('a')])
}=={
frozenset([frozenset('a') , frozenset('b')])
}
Output: True

It seems Multiset can not perfectly inherit attributes of set ???

**Comment by wheerd** [comment]
It looks like you are not putting the same things in though in your examples:
`frozenset({'a'})` vs. frozenset('a')
