### ISSUE TITLE
.values() not implemented, __str__() is unweildy

### ISSUE THREAD

**Issue by 0racle** [wheerd/multiset#3]
Firstly, thanks for the module. There's 2 minor issues, sorry to cram them into one heap.

  1. The documentation mentions `.values()` as a synonym for `.multiplicities()`, however this does not work. I would prefer `.values()` to work as documented (rather than say, deleting it from the docs). This would be consistent with the multiset working with other standard `dict` methods.

  2. When dealing with large multisets, I am forced to do `print(mset.__repr__())` because to the default `.__str__()` produces unwieldy output

```python
>>> mset = Multiset({'Pumpkin': 1, 'Eggs': 3, 'Milk': 4, 'Sugar': 30})      
>>> print(mset.__repr__())
Multiset({'Pumpkin': 1, 'Eggs': 3, 'Milk': 4, 'Sugar': 30})
>>> print(mset)          
{Pumpkin, Eggs, Eggs, Eggs, Milk, Milk, Milk, Milk, Sugar, Sugar, Sugar, Sugar, Sugar, Sugar, Sugar, Sugar, Sugar, Sugar, Sugar, Sugar, Sugar, Sugar, Sugar, Sugar, Sugar, Sugar, Sugar, Sugar, Sugar, Sugar, Sugar, Sugar, Sugar, Sugar, Sugar, Sugar, Sugar, Sugar}
```

Multisets are often notated in a concise form, as referenced [here](https://oeis.org/wiki/Multisets)

  > the multiset `{a, a, a, a, a, b, b, b, c, d, d}` ,which may be written in compact form as the map `{a: 5, b: 3, c: 1, d: 2}`, where for each distinct member we specify the multiplicity.

So I think the `.__repr__()` is perfectly acceptable stringification under all circumstances. If I need the entire list, I can always `list(mset)`.

**Comment by wheerd** [comment]
1. That is a bug which occurred because of a change in the implementation. Do you want to create a pull request? Otherwise, I will fix it on the weekend.
2. You can also write `repr(mset)` which is nicer. The problem with your proposal is that it works nicely for string, but if the objects in the set have a complicated `__repr__` then that get pretty unwieldy. You can always create your own subclass to implement this behavior. I am open to adding some method for this kind of representation though.

**Comment by 0racle** [comment]
1. If I have time I will write a pull request.

  2. That's fair enough. I wrote an (unpublished) Multiset lib for Perl 5, mainly using Perl 6's built in multisets, and your lib as reference points. I also ran into the question of how to handle stringification with multisets of complex objects. Eventually I created a "lite" multiset sub-type, because I realised that more often than not my multisets used strings as keys. I dunno why I bring this up... but I understand the reason for your decision, so you can ignore part 2 of the issue.

PS. I dunno if this is worth raising another issue over, but I noticed your lib doesn't support `set - Multiset` operations.

```python
>>> set('ac') - Multiset('aab')              
TypeError: unsupported operand type(s) for -: 'set' and 'Multiset'
```

Is this a bug, or a purposeful omission? FWIW, Perl 6 treats the Set on the LHS like a Multiset for this operation, and returns a new Multiset

```perl6
> Set('a', 'c') ∖ Bag('a', 'a', 'b')
Bag(c)
```

**Comment by wheerd** [comment]
That is an oversight on my part. Because the difference is not symmetric I did not implement `__rsub__`.

**Comment by wheerd** [comment]
Done in 2.1.1.
