### ISSUE TITLE
Unnecessary copying and sorting in FrozenMultiset __hash__

### ISSUE THREAD

**Issue by MikeFHay** [wheerd/multiset#51]
`__hash__` in FrozenMultiset is implemented as `return hash(tuple(sorted(self._elements.items())))`. This is simple and correctly results in a hash value that does not depend on the order of items, but it is presumably quite slow and will fail if the elements are not orderable.
I would have to test to be sure, but I believe that a solution of simply summing the hashes, like [Java's AbstractMap](https://github.com/openjdk/jdk/blob/master/src/java.base/share/classes/java/util/AbstractMap.java#L523), would be faster and work for all hashable entries.

**Comment by MikeFHay** [comment]
I have created a pulll request. I did some benchmarking with timeit like so:

```
def test_hash_performance(capsys):
  with capsys.disabled():
    ns = list(range(1000))
    random.shuffle(ns)
    ms = FrozenMultiset(ns)
    print('length: ', len(ms))
    print('hash')
    print(timeit.timeit(lambda: ms.__hash__(), number=10000))
    print('sort_hash')
    print(timeit.timeit(lambda: ms.sort_hash(), number=10000))
    print('list_hash')
    print(timeit.timeit(lambda: ms.list_hash(), number=10000))
```

Where `hash` is my new implementation, `sort_hash` is the old implementation, and `list_hash` is my new implementation but using a list comprehension instead of a generator comprehension. The results for various input sizes are:

```
length:  10000
hash
62.07562967400008
sort_hash
164.12361728100223
list_hash
58.687616625989904

length: 1000
hash
6.088054256004398
sort_hash
10.759474309001234
list_hash
5.414320561001659

length:  100
hash
0.5892152259912109
sort_hash
0.6641982709988952
list_hash
0.5106893349875463

length:  10
hash
0.08341519499663264
sort_hash
0.08962682000128552
list_hash
0.08621509000658989
```

These were run on replit. The new implementation is consistently faster than the old. The list implementation benchmarks 5-10% faster than the generator, but I think the harder-to-measure benefits of reduced allocation justify sticking with the generator instead of an intermediate list.

**Comment by wheerd** [comment]
Hey @MikeFHay, thank you for your PR! I'm not sure whether just summing up the hashes is a good idea in terms of preserving the uniform distribution of hashes. I would rather stay with using the hash implementation of a built-in data structure. I looked a bit into it and I think using `frozenset` instead of a sorted tuple might be faster. What do you think?

**Comment by wheerd** [comment]
I released a new version, thank you for your contribution!
